nnoremap <leader>p 0cwpickup<esc>0
nnoremap <leader>r 0cwreword<esc>0
nnoremap <leader>e 0cwedit<esc>0
nnoremap <leader>s 0cwsquash<esc>0
nnoremap <leader>f 0cwfixup<esc>0
nnoremap <leader>x 0cwexec<esc>0
nnoremap <leader>b 0cwbreak<esc>0
nnoremap <leader>d 0cwdrop<esc>0
nnoremap <leader>l 0cwlabel<esc>0
nnoremap <leader>t 0cwreset<esc>0
nnoremap <leader>m 0cwmerge<esc>0
