select = ["ALL"]
ignore = [
    "ANN101",
    "ANN401",
    "PTH",
    "TD002",
    "TD003",
]
fixable = ["ALL"]
unfixable = [
    "F841",
]
line-length = 79
target-version = "py38"

[pydocstyle]
convention = "google"

[per-file-ignores]
".pythonrc" = ["D100"]
