line-length = 79
target-version = "py38"

[lint]
select = ["ALL"]
ignore = [
    "ANN101",
    "ANN401",
    "COM812",
    "D",
    "ISC001",
    "PTH",
    "TD002",
    "TD003",
]
fixable = ["ALL"]

[lint.pydocstyle]
convention = "google"

[format]
preview = true
