" Set utf-8 as standard encoding and en_US as the standard language.
set encoding=utf-8

filetype plugin on  " Enable loading of plugin file.
filetype indent on  " Enable loading of indent file.

" ================= General =================

set history=500   " Increase the size of the undo queue.
set noerrorbells  " Turn off the error bells.
set novisualbell  " Turn off the visual bell.

" In some cases, noerrorbells doesn't seems to be enough to completely disable
" the annoying warning.
if !has("unix")
    set belloff=all
endif

" Turn off swap files.
set nobackup
set noswapfile

" ================ Interface ================

set title   " Add the current file to the terminal title.
set number  " Display the line number.
set ruler   " Always show the cursor.

" Turn on syntax highlighting.
syntax on

" Display a vertical bar at the 79 column.
set colorcolumn=79

" Always show the status line.
"     0: never
"     1: only if there are at least two windows
"     2: always
set laststatus=2

" ================= Editor =================

set nowrap       " Disable the wrap line.
set linebreak    " Wrap lines at convenient points.

set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set autoindent
set smartindent

" ================= Search =================

set ignorecase  " Ignore case when searching.
set smartcase   " When searching try to be smart about cases
set hlsearch    " Highlight search results.
set incsearch   " Make search act like search in modern browsers.

" =============== Completion ===============

set wildmenu                    " Turn on wildmenu.
set wildmode=list:longest       " ...
set wildignore=
set wildignore+=*.pyc           " Python2 bytes-compiled files.
set wildignore+=__pycache__/**  " Python3 bytes-compiled files.
set wildignore+=.DS_Store       " File generated by MacOS

" ================== Folds ==================

set foldmethod=indent  " Fold based on indent.
set foldnestmax=3      " Deepest fold is 3 levels.
set nofoldenable       " Dont fold by default.

" ================= Mapping =================

" Define leader keys.
let mapleader=","
let maplocalleader="-"

" Quickly edit and source .vimrc file.
nnoremap <leader>ev :split $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Easy access to normal mode.
inoremap jk <esc>

" Move line up and down.
nnoremap <c-j> :move .+1<cr>==
nnoremap <c-k> :move .-2<cr>==
vnoremap <c-j> :move '>+1<cr>gv=gv
vnoremap <c-k> :move '<-2<cr>gv=gv

" Move to the first/last character of the line.
nnoremap L $
nnoremap H ^

" Quote selection.
vnoremap <leader>' di'<esc>pa'<esc>
vnoremap <leader>" di"<esc>pa"<esc>

" Split line.
nnoremap K i<cr><esc>k==$

" Natural Indent.
nnoremap <tab> >>
nnoremap <s-tab> <<
vnoremap <tab> >gv
vnoremap <s-tab> <gv
