# Starship configuration file.
#
# Description:
#
#   A minimal, blazing-fast, and infinitely customizable prompt for any shell!
#
# Location:
#
#   ~/.config/starship.toml
#

# Get editor completions based on the config schema.
"$schema" = 'https://starship.rs/config-schema.json'

# Insert a new blank line bedore the prompt.
add_newline = true
