# Configuration file for starship prompt.
#
# Description:
#
#   A minimal, blazing-fast, and infinitely customizable prompt for any shell!
#
# Location:
#
#   ~/.config/starship.toml
#

# Get editor completions based on the config schema.
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts.
add_newline = true

[shell]
disabled = false
fish_indicator = ""
powershell_indicator = "_"
