# Starship configuration file.

# Get editor completions based on the config schema.
"$schema" = "https://starship.rs/config-schema.json"

# Insert a new blank line bedore the prompt.
add_newline = true

[directory]
style = "bold blue"
