return require("packer").startup(function()
    use {"dag/vim-fish"}
    use {"drewtempelmeyer/palenight.vim"}
    use {"folke/lsp-colors.nvim"}
    use {"folke/trouble.nvim"}
    use {"glepnir/lspsaga.nvim"}
    use {"hrsh7th/cmp-nvim-lsp"}
    use {"hrsh7th/nvim-cmp"}
    use {"jose-elias-alvarez/null-ls.nvim"}
    use {"kyazdani42/nvim-web-devicons"}
    use {"neovim/nvim-lspconfig"}
    use {"ntpeters/vim-better-whitespace"}
    use {"nvim-lua/plenary.nvim"}
    use {"nvim-lualine/lualine.nvim"}
    use {"nvim-telescope/telescope.nvim"}
    use {"nvim-treesitter/nvim-treesitter"}
    use {"onsails/lspkind.nvim"}
    use {"wbthomason/packer.nvim"}
end)
