# Settings used for Bash shell (non-login).
#
# Description:
#
#   Shell script that Bash will execute when it is started in an non-login
#   mode (when your are already logged ans open a new terminal for example).
#   It is used to determine and tell the shell how it should looks and act.
#
#   Possible configuration include appearance, prompt, alias...
#
# Location:
#
#   ~/.bashrc
#

# Aliases.
alias la="ls -al"
alias ll="ls -l"
alias refresh="source ~/.bash_profile"
alias tmp="cd $TMPDIR"

# Disable MacOs warning on shell start.
export BASH_SILENCE_DEPRECATION_WARNING=1

# Enable colors.
export CLICOLOR=1

# Add some facility to the interactive python interpreter.
export PYTHONSTARTUP="$HOME/.pythonrc"

# Create a tree like command on windows.
if [[ "$OSTYPE" == "msys" ]]; then
    alias tree="cmd //c tree"
fi

# Add executable to PATH.
export PATH+=:~/bin

# Load starship.
eval "$(starship init bash)"
